### ISSUE TITLE
Errors on world.tsc

### ISSUE THREAD

**Issue by PasqualeS91** [davcri/scopgame-GithubGameOff17#15]
![schermata del 2017-11-11 19-38-06](https://user-images.githubusercontent.com/7521541/32692423-0f74202a-c718-11e7-9d93-724cfb952057.png)

**Comment by davcri** [comment]
This fixes the stream player error: https://github.com/davcri/scopgame-GithubGameOff17/commit/5e1099785dee1db2b891e12e20b2d3e49652022f
