### ISSUE TITLE
Reorganize scenes

### ISSUE THREAD

**Issue by davcri** [davcri/scopgame-GithubGameOff17#18]
- [x] Move Player node in a common scene inside  `game/scenes/common/Player`
- [x] Create a new scene called `Level1`where to put only map and level related stuff. From this scene we can instance common nodes such as the Player, Collectibles, ecc.

**Comment by davcri** [comment]
To avoid conflicts: before handling this issue, we should merge all our branches into develop.  
Create pull requests, so that tomorrow we can close this issue.

@SilvioC90 @PasqualeS91 @Paflo

**Comment by davcri** [comment]
A possible improvement is to change from what we have now (on the left) to what is shown on the right. 
We surely need to fix some dependencies.

In the pictures I opened only the first sublevel of child nodes.

![schermata da 2017-11-13 18-25-16](https://user-images.githubusercontent.com/6860637/32739801-3cc3d4b4-c8a1-11e7-8c97-440b91b9627a.png)

**Comment by PasqualeS91** [comment]
non conviene farlo adesso
