### ISSUE TITLE
Convenzione uso dei branch 

### ISSUE THREAD

**Issue by davcri** [davcri/scopgame-GithubGameOff17#3]
@SilvioC90 chiedo una tua review: https://github.com/davcri/scopgame-GithubGameOff17/blob/develop/CONTRIBUTING.md

**Comment by SilvioC90** [comment]
Va benissimo. Va bene anche la cosa di usare develop per i fix tanto in un
mese non ha senso usare anche hotfix. Ottimo lavoro.

Silvio

Il 05 nov 2017 22:10, "Davide Cristini" <notifications@github.com> ha
scritto:
