### ISSUE TITLE
Jump while falling

### ISSUE THREAD

**Issue by SilvioC90** [davcri/scopgame-GithubGameOff17#7]
The character can jump while he falls if he has not pressed "jump" button before falling.

One possible fix would be to change this condition:
`if jump_count < MAX_JUMP_COUNT and event.is_action_pressed("jump"):`
with this one:
`if jump_count < MAX_JUMP_COUNT and event.is_action_pressed("jump") and speed.y == 0:`
which checks if the speed on y axis is zero (false if the character was falling or flying up).

**Comment by davcri** [comment]
Great 😈
